# Generated by Django 5.2.4 on 2025-09-02 21:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_total', models.IntegerField()),
                ('qtd_disponivel', models.IntegerField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo')),
                ('tamanho', models.CharField(max_length=10)),
                ('voltagem', models.CharField(blank=True, choices=[('110v', '110v'), ('220v', '220v'), ('bivolt', 'Bivolt')], null=True)),
                ('energia', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True)),
                ('inflavel', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parcelado', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True)),
                ('qtd_parcelas', models.IntegerField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(default='S/N', max_length=5)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_festa', models.DateField()),
                ('hora_festa', models.TimeField()),
                ('duracao', models.CharField(choices=[('3h', '3 hora'), ('4h', '4 hora'), ('5h', '5 horas'), ('6h', '6 horas'), ('7h', '7 horas'), ('8h', '8 horas'), ('9h', '9 horas'), ('10h', '10 horas')], default='8h')),
                ('hora_montagem', models.TimeField()),
                ('data_desmontagem', models.DateField()),
                ('hora_desmontagem', models.TimeField()),
                ('montador', models.CharField(max_length=100)),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('valor_restante', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('acrescimos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('descontos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pagamento', models.CharField(choices=[('nao_pago', 'Não Pago'), ('entrada', 'Entrada Paga'), ('pago', 'Pago')], default='nao_pago', max_length=20)),
                ('qtd_parcelas', models.IntegerField(default='1')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('montado', 'Montado'), ('recolher', 'Recolher'), ('finalizado', 'Finalizado')], default='pendente')),
                ('metodo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'Pix')], default='pix')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(default='S/N', max_length=5)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('brinquedos', models.ManyToManyField(to='core.brinquedo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos_anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locacao')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='locacao',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='core.organization'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.organization'),
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brinquedos', to='core.organization'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('membro', 'Membro')], default='membro', max_length=10)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('data_transacao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=8)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('manutencao', 'Manutenção'), ('salario', 'Salário'), ('compra', 'Compra'), ('investimento', 'Investimento'), ('pagamento', 'Pagamento'), ('combustivel', 'Combustível'), ('outro', 'Outro')], max_length=12)),
                ('pagamento', models.CharField(choices=[('pago', 'Pago'), ('entrada', 'Entrada'), ('nao_pago', 'Não Pago'), ('planejado', 'Planejado'), ('cancelado', 'Cancelado')], max_length=10)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('parcelado', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('locacao', 'Locação'), ('investimento_brinquedo', 'Investimento Brinquedo')], max_length=23)),
                ('qtd_parcelas', models.IntegerField(blank=True, null=True)),
                ('parcela_atual', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('brinquedo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brinquedo')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('locacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locacao')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.organization')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data_transacao', 'id'],
            },
        ),
    ]
