# Generated by Django 5.2.4 on 2025-07-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_total', models.IntegerField()),
                ('qtd_disponivel', models.IntegerField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo')),
                ('tamanho', models.CharField(max_length=10)),
                ('voltagem', models.CharField(blank=True, choices=[('110v', '110v'), ('220v', '220v'), ('bivolt', 'Bivolt')], null=True)),
                ('energia', models.BooleanField(blank=True, null=True)),
                ('inflavel', models.BooleanField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
