# Generated by Django 5.2.4 on 2025-09-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_convite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convite',
        ),
    ]
