# Generated by Django 5.2.4 on 2025-07-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brinquedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='energia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='inflavel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
