# Generated by Django 5.2.4 on 2025-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_brinquedo_energia_alter_brinquedo_inflavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='energia',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True),
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='inflavel',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True),
        ),
    ]
