# Generated by Django 5.2.4 on 2025-07-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_brinquedo_energia_alter_brinquedo_inflavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='S/N', max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_festa', models.DateField()),
                ('hora_festa', models.TimeField()),
                ('duracao', models.CharField(choices=[('3h', '3 hora'), ('4h', '4 hora'), ('5h', '5 horas'), ('6h', '6 horas'), ('7h', '7 horas'), ('8h', '8 horas'), ('9h', '9 horas'), ('10h', '10 horas')], default='8h')),
                ('hora_montagem', models.TimeField()),
                ('data_desmontagem', models.DateField()),
                ('hora_desmontagem', models.TimeField()),
                ('montador', models.CharField(max_length=100)),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd_parcelas', models.IntegerField(default='1')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('montado', 'Montado'), ('recolher', 'Recolher'), ('finalizado', 'Finalizado')], default='pendente')),
                ('metodo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'Pix')], default='pix')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(default='S/N', max_length=5)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('brinquedos', models.ManyToManyField(to='core.brinquedo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
        ),
    ]
