# Generated by Django 5.2.4 on 2025-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_cep_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='acrescimos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacao',
            name='descontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
