# Generated by Django 5.2.4 on 2025-08-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_locacao_acrescimos_locacao_descontos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos_anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locacao')),
            ],
        ),
    ]
