# Generated by Django 5.2.4 on 2025-08-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contratoanexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizarStatusRecolher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
