# Generated by Django 5.2.4 on 2025-08-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_atualizarstatusrecolher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtualizarStatusRecolher',
        ),
        migrations.AddField(
            model_name='locacao',
            name='pagamento',
            field=models.CharField(choices=[('nao_pago', 'Não Pago'), ('entrada', '30% Pago'), ('pago', 'Pago')], default='nao_pago', max_length=20),
        ),
    ]
