# Generated by Django 5.2.4 on 2025-08-08 02:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_atualizarstatusrecolher_locacao_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='valor_restante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
