# Generated by Django 5.2.4 on 2025-08-12 03:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_locacao_valor_restante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_transacao', models.DateField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=8)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('manutencao', 'Manutenção'), ('salario', 'Salário'), ('compra', 'Compra'), ('pagamento', 'Pagamento'), ('gasolina', 'Gasolina'), ('outro', 'Outro')], max_length=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('planejado', 'Planejado'), ('cancelado', 'Cancelado')], max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('locacao', 'Locação')], max_length=10)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('parcelamento_total', models.IntegerField(blank=True, null=True)),
                ('parcelamento_num', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='locacao',
            name='acrescimos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='descontos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_restante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
