# Generated by Django 5.2.4 on 2025-08-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transacoes_alter_locacao_acrescimos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='categoria',
            field=models.CharField(choices=[('aluguel', 'Aluguel'), ('manutencao', 'Manutenção'), ('salario', 'Salário'), ('compra', 'Compra'), ('pagamento', 'Pagamento'), ('combustivel', 'Combustível'), ('outro', 'Outro')], max_length=12),
        ),
    ]
