# Generated by Django 5.2.4 on 2025-08-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_transacoes_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacoes',
            options={'ordering': ['-data_transacao', '-id'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='referencia_id',
        ),
        migrations.AddField(
            model_name='transacoes',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='locacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locacao'),
        ),
    ]
