# Generated by Django 5.2.4 on 2025-08-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_transacoes_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('entrada', '30% Pago'), ('planejado', 'Planejado'), ('cancelado', 'Cancelado')], max_length=10),
        ),
    ]
