# Generated by Django 5.2.4 on 2025-08-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_transacoes_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacoes',
            old_name='status',
            new_name='pagamento',
        ),
    ]
