# Generated by Django 5.2.4 on 2025-08-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_status_transacoes_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('entrada', '30% Pago'), ('planejado', 'Planejado'), ('cancelado', 'Cancelado')], max_length=10),
        ),
    ]
