# Generated by Django 5.2.4 on 2025-08-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_transacoes_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacoes',
            options={'ordering': ['-data_transacao', 'id'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
