# Generated by Django 5.2.4 on 2025-08-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_transacoes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='parcelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='qtd_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='valor_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
