# Generated by Django 5.2.4 on 2025-08-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_brinquedo_data_aquisicao_brinquedo_parcelado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='parcelado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True),
        ),
    ]
