# Generated by Django 5.2.4 on 2025-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_brinquedo_parcelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
