# Generated by Django 5.2.4 on 2025-08-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_brinquedo_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brinquedo',
            name='valor_diaria',
        ),
        migrations.AddField(
            model_name='brinquedo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
