# Generated by Django 5.2.4 on 2025-08-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_brinquedo_valor_diaria_brinquedo_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brinquedo',
            old_name='valor',
            new_name='valor_diaria',
        ),
        migrations.AlterField(
            model_name='brinquedo',
            name='valor_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
