# Generated by Django 5.2.4 on 2025-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_valor_brinquedo_valor_diaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('locacao', 'Locação'), ('brinquedo', 'Brinquedo')], max_length=10),
        ),
    ]
