# Generated by Django 5.2.4 on 2025-08-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_transacoes_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('locacao', 'Locação'), ('investimento_brinquedo', 'Investimento Brinquedo')], max_length=23),
        ),
    ]
