# Generated by Django 5.2.4 on 2025-08-24 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_transacoes_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='brinquedo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brinquedo'),
        ),
    ]
