# Generated by Django 5.2.4 on 2025-08-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_transacoes_brinquedo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacoes',
            old_name='parcelamento_num',
            new_name='parcelas_atual',
        ),
        migrations.RenameField(
            model_name='transacoes',
            old_name='parcelamento_total',
            new_name='qtd_parcelas',
        ),
        migrations.AddField(
            model_name='transacoes',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='parcelado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True),
        ),
    ]
