# Generated by Django 5.2.4 on 2025-08-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_parcelamento_num_transacoes_parcelas_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='parcelado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao'),
        ),
    ]
