# Generated by Django 5.2.4 on 2025-08-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_brinquedo_parcelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='parcelado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], null=True),
        ),
    ]
