# Generated by Django 5.2.4 on 2025-08-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_brinquedo_parcelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='referencia_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
