# Generated by Django 5.2.4 on 2025-08-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_transacoes_referencia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacoes',
            old_name='parcelas_atual',
            new_name='parcela_atual',
        ),
    ]
