# Generated by Django 5.2.4 on 2025-07-14 01:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=None)),
                ('cep', models.CharField(default='85260-000', max_length=20)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(default='S/N', max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=100, null=None)),
                ('cidade', models.CharField(default='Manoel Ribas', max_length=100)),
                ('estado', models.CharField(default='Paraná', max_length=100)),
                ('pais', models.CharField(default='Brasil', max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=255, null=None)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_festa', models.DateField()),
                ('hora_festa', models.TimeField(blank=True, null=True)),
                ('duração', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('hora_montagem', models.TimeField(blank=True, null=True)),
                ('data_retirada', models.DateField()),
                ('hora_retirada', models.TimeField(blank=True, null=True)),
                ('montador', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qtd_parcelas', models.PositiveIntegerField(default=1)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'PIX')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando', 'Aguardando'), ('entregue', 'Entregue'), ('finalizado', 'Finalizado')], default='pendente', max_length=20)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('brinquedos', models.ManyToManyField(to='locacoes.brinquedo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacoes.cliente')),
            ],
            options={
                'ordering': ['-data_festa', '-hora_festa'],
            },
        ),
    ]
