# Generated by Django 5.2.4 on 2025-07-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='data_festa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
