# Generated by Django 5.2.4 on 2025-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0003_alter_locacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='quantidade',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
