# Generated by Django 5.2.4 on 2025-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0004_brinquedo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='brinquedo',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
