# Generated by Django 5.2.4 on 2025-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0005_brinquedo_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='cep',
            field=models.CharField(default='85260000', max_length=10),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='cidade',
            field=models.CharField(default='Maneol Ribas', max_length=100),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='numero',
            field=models.CharField(default='S/N', max_length=10),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='rua',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='uf',
            field=models.CharField(default='PR', max_length=2),
        ),
    ]
