# Generated by Django 5.2.4 on 2025-07-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0006_alter_locacao_cep_alter_locacao_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='metodo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('Pix', 'PIX')], max_length=20),
        ),
    ]
