# Generated by Django 5.2.4 on 2025-07-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0009_alter_locacao_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão'), ('Pix', 'Pix')], max_length=20),
        ),
    ]
