# Generated by Django 5.2.4 on 2025-07-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0010_alter_locacao_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
    ]
