# Generated by Django 5.2.4 on 2025-07-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0014_alter_locacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='Pendente', max_length=20),
        ),
    ]
